package mx.ipn.upiicsa.portal_admon.pojo;
// Generated 22/07/2017 04:38:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BeaconDepartamento generated by hbm2java
 */
public class BeaconDepartamento  implements java.io.Serializable {


     private Integer id;
     private Beacon beacon;
     private Departamento departamento;
     private Date fechaAlta;
     private String usuarioAlta;
     private int status;

    public BeaconDepartamento() {
    }

    public BeaconDepartamento(Beacon beacon, Departamento departamento, Date fechaAlta, String usuarioAlta, int status) {
       this.beacon = beacon;
       this.departamento = departamento;
       this.fechaAlta = fechaAlta;
       this.usuarioAlta = usuarioAlta;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Beacon getBeacon() {
        return this.beacon;
    }
    
    public void setBeacon(Beacon beacon) {
        this.beacon = beacon;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public String getUsuarioAlta() {
        return this.usuarioAlta;
    }
    
    public void setUsuarioAlta(String usuarioAlta) {
        this.usuarioAlta = usuarioAlta;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


