package mx.ipn.upiicsa.portal_admon.pojo;
// Generated 22/07/2017 04:38:28 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Beacon generated by hbm2java
 */
public class Beacon  implements java.io.Serializable {


     private Integer id;
     private String codigo;
     private String descripcion;
     private String uuid;
     private String numeroSerie;
     private Date fechaAlta;
     private String usuarioAlta;
     private int status;
     private Set beaconDepartamentos = new HashSet(0);
     private Set promocionBeacons = new HashSet(0);

    public Beacon() {
    }

	
    public Beacon(String codigo, String descripcion, String uuid, String numeroSerie, Date fechaAlta, String usuarioAlta, int status) {
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.uuid = uuid;
        this.numeroSerie = numeroSerie;
        this.fechaAlta = fechaAlta;
        this.usuarioAlta = usuarioAlta;
        this.status = status;
    }
    public Beacon(String codigo, String descripcion, String uuid, String numeroSerie, Date fechaAlta, String usuarioAlta, int status, Set beaconDepartamentos, Set promocionBeacons) {
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.uuid = uuid;
       this.numeroSerie = numeroSerie;
       this.fechaAlta = fechaAlta;
       this.usuarioAlta = usuarioAlta;
       this.status = status;
       this.beaconDepartamentos = beaconDepartamentos;
       this.promocionBeacons = promocionBeacons;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    public String getNumeroSerie() {
        return this.numeroSerie;
    }
    
    public void setNumeroSerie(String numeroSerie) {
        this.numeroSerie = numeroSerie;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public String getUsuarioAlta() {
        return this.usuarioAlta;
    }
    
    public void setUsuarioAlta(String usuarioAlta) {
        this.usuarioAlta = usuarioAlta;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Set getBeaconDepartamentos() {
        return this.beaconDepartamentos;
    }
    
    public void setBeaconDepartamentos(Set beaconDepartamentos) {
        this.beaconDepartamentos = beaconDepartamentos;
    }
    public Set getPromocionBeacons() {
        return this.promocionBeacons;
    }
    
    public void setPromocionBeacons(Set promocionBeacons) {
        this.promocionBeacons = promocionBeacons;
    }




}


