package mx.ipn.upiicsa.portal_admon.pojo;
// Generated 22/07/2017 04:38:28 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CadenaComercial generated by hbm2java
 */
public class CadenaComercial  implements java.io.Serializable {


     private int id;
     private String codigo;
     private String descripcion;
     private Date fechaAlta;
     private String usuarioAlta;
     private int status;
     private String cadenaComercialcol;
     private Set sucursals = new HashSet(0);

    public CadenaComercial() {
    }

	
    public CadenaComercial(int id, String codigo, String descripcion, Date fechaAlta, String usuarioAlta, int status) {
        this.id = id;
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.fechaAlta = fechaAlta;
        this.usuarioAlta = usuarioAlta;
        this.status = status;
    }
    public CadenaComercial(int id, String codigo, String descripcion, Date fechaAlta, String usuarioAlta, int status, String cadenaComercialcol, Set sucursals) {
       this.id = id;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.fechaAlta = fechaAlta;
       this.usuarioAlta = usuarioAlta;
       this.status = status;
       this.cadenaComercialcol = cadenaComercialcol;
       this.sucursals = sucursals;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public String getUsuarioAlta() {
        return this.usuarioAlta;
    }
    
    public void setUsuarioAlta(String usuarioAlta) {
        this.usuarioAlta = usuarioAlta;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public String getCadenaComercialcol() {
        return this.cadenaComercialcol;
    }
    
    public void setCadenaComercialcol(String cadenaComercialcol) {
        this.cadenaComercialcol = cadenaComercialcol;
    }
    public Set getSucursals() {
        return this.sucursals;
    }
    
    public void setSucursals(Set sucursals) {
        this.sucursals = sucursals;
    }




}


