package mx.ipn.upiicsa.portal_admon.pojo;
// Generated 22/07/2017 04:38:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PromocionBeacon generated by hbm2java
 */
public class PromocionBeacon  implements java.io.Serializable {


     private int id;
     private Beacon beacon;
     private Promocion promocion;
     private Date fechaAlta;
     private String usuarioAlta;
     private int status;

    public PromocionBeacon() {
    }

    public PromocionBeacon(int id, Beacon beacon, Promocion promocion, Date fechaAlta, String usuarioAlta, int status) {
       this.id = id;
       this.beacon = beacon;
       this.promocion = promocion;
       this.fechaAlta = fechaAlta;
       this.usuarioAlta = usuarioAlta;
       this.status = status;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Beacon getBeacon() {
        return this.beacon;
    }
    
    public void setBeacon(Beacon beacon) {
        this.beacon = beacon;
    }
    public Promocion getPromocion() {
        return this.promocion;
    }
    
    public void setPromocion(Promocion promocion) {
        this.promocion = promocion;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public String getUsuarioAlta() {
        return this.usuarioAlta;
    }
    
    public void setUsuarioAlta(String usuarioAlta) {
        this.usuarioAlta = usuarioAlta;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


