package mx.ipn.upiicsa.portal_admon.pojo;
// Generated 22/07/2017 04:38:28 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoPromocion generated by hbm2java
 */
public class TipoPromocion  implements java.io.Serializable {


     private int id;
     private String codigo;
     private String descripcion;
     private Date fechaAlta;
     private String usuarioAlta;
     private int status;
     private Set promocions = new HashSet(0);

    public TipoPromocion() {
    }

	
    public TipoPromocion(int id, String codigo, String descripcion, Date fechaAlta, String usuarioAlta, int status) {
        this.id = id;
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.fechaAlta = fechaAlta;
        this.usuarioAlta = usuarioAlta;
        this.status = status;
    }
    public TipoPromocion(int id, String codigo, String descripcion, Date fechaAlta, String usuarioAlta, int status, Set promocions) {
       this.id = id;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.fechaAlta = fechaAlta;
       this.usuarioAlta = usuarioAlta;
       this.status = status;
       this.promocions = promocions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public String getUsuarioAlta() {
        return this.usuarioAlta;
    }
    
    public void setUsuarioAlta(String usuarioAlta) {
        this.usuarioAlta = usuarioAlta;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Set getPromocions() {
        return this.promocions;
    }
    
    public void setPromocions(Set promocions) {
        this.promocions = promocions;
    }




}


