package mx.ipn.upiicsa.portal_admon.pojo;
// Generated 22/07/2017 04:38:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private RolUsuario rolUsuario;
     private String usuario;
     private String contrasenia;
     private String nombreCompleto;
     private String correo;
     private Date fechaAlta;
     private String usuarioAlta;
     private int status;

    public Usuario() {
    }

    public Usuario(int id, RolUsuario rolUsuario, String usuario, String contrasenia, String nombreCompleto, String correo, Date fechaAlta, String usuarioAlta, int status) {
       this.id = id;
       this.rolUsuario = rolUsuario;
       this.usuario = usuario;
       this.contrasenia = contrasenia;
       this.nombreCompleto = nombreCompleto;
       this.correo = correo;
       this.fechaAlta = fechaAlta;
       this.usuarioAlta = usuarioAlta;
       this.status = status;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public RolUsuario getRolUsuario() {
        return this.rolUsuario;
    }
    
    public void setRolUsuario(RolUsuario rolUsuario) {
        this.rolUsuario = rolUsuario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public String getUsuarioAlta() {
        return this.usuarioAlta;
    }
    
    public void setUsuarioAlta(String usuarioAlta) {
        this.usuarioAlta = usuarioAlta;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


